DROP TABLE IF EXISTS `brands`;
CREATE TABLE `brands` (
                        `id` int(11) NOT NULL,
                        `url` varchar(255) NOT NULL DEFAULT '--',
                        `title` varchar(255) NOT NULL DEFAULT '--',
                        `description` varchar(1000) NOT NULL DEFAULT '--',
                        `url1` varchar(255) NOT NULL DEFAULT '--',
                        `url2` varchar(255) NOT NULL DEFAULT '--',
                        `url3` varchar(255) NOT NULL DEFAULT '--',
                        `link1` varchar(255) NOT NULL DEFAULT '--',
                        `link2` varchar(255) NOT NULL DEFAULT '--',
                        `link3` varchar(255) NOT NULL DEFAULT '--',
                        `iframe` varchar(255) NOT NULL DEFAULT '--'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


INSERT INTO `brands` (`id`, `url`, `title`, `description`, `url1`, `url2`, `url3`, `link1`, `link2`, `link3`, `iframe`) VALUES
(1, 'vox-guitar.png', 'VOX', 'VSS-1P BK. Otras guitarra eléctricas. Guitarra eléctrica VOX Starstream. Nuevo modelo Type 1 PLUS. Incluye un modo pasivo, sin necesidad de alimentación al sistema de modelado, y un sistema de modelado de sonidos actualizado. Sistema Incorporado: S', 'https://www.leturiaga.com/guitarras/058547-otras-guitarras-electricas-vox-vss-1p-bk.html?gclid=CjwKCAjwza_mBRBTEiwASDWVvtqUpZa-qMQM8ysSAtI67O2pUPA9dt2hWPZ4irb7Vx_-vWz1Vj7zPRoCKYQQAvD_BwE#tab-label-description', 'https://www.amazon.es/Vox-vss-1p-rd-starstream-Type-1-Plus-Passive/dp/B078P4DYQB', 'https://www.gear4music.es/es/Guitarra-y-bajo/Vox-Starstream-Type-1-Plus-Mahogany-Red/2ATX', 'Leturiaga', 'Amazaon', 'Gear4Music', 'https://www.youtube.com/embed/1Ov6xt5_9HA'),
(2, 'yamaha_pacific.png', 'Yamaha Pacific', 'Esta Guitarra Eléctrica de Yamaha para principiantes ofrece características comprensivas, calidad artesanal y un gran sonido y relación calidad-precio insuperable.', 'https://www.musisol.com/es/guitarras-electricas/yamaha-pac112j-yns-yellow-natural-satin.html?gclid=CjwKCAjw8LTmBRBCEiwAbhh-6FwdYJkBL8c45ddD_UySlXsS21MS9PMftwTyao5iS39HrjW1pMHC_RoCJ4kQAvD_BwE', 'https://www.amazon.es/Yamaha-PACIFICA-012-Guitarra-el%C3%A9ctrica/dp/B00123DQT6', 'https://www.gear4music.es/es/Guitarra-y-bajo/Yamaha-Pacifica-012-Guitarra-Electrica-Azul-Metalizado/40C', 'Musisol', 'Amazon', 'Gear4Music', 'https://www.youtube.com/embed/nBaQny0v-Hg'),
(3, 'knoxvile.png', 'Gear4Music Knoxville', 'Con un diseño clásico, esta guitarra ofrece características profesionales y tonales de alta calidad a un precio asequible. Ideal para tocar todo tipo de estilos musicales clásicos. ', 'https://www.gear4music.es/es/Guitarra-y-bajo/Guitarra-Electrica-Knoxville-de-Gear4music-Natural/CBM', '', '', 'Gear4Music', '', '', 'https://www.youtube.com/embed/u1F4QlO7nns'),
(4, 'ibanez.png', 'Ibanez GRG', 'La Ibanez GRG170DX es la guitarra de metal por antonomasia. Su configuración de pastillas proporciona el tono potente y pesado que estás buscando. Construida a partir de un cuerpo de caoba con mástil de arce atornillado y diapasón de palisandro de 24 trastes jumbo, la GRG170DX produce un tono completo, actual y es tremendamente rápida. También cuenta con un trémolo FAT-10, pastillas Infinity de bobina simple y humbuckers, afinadores de cromo y controles redondeados, haciendo de la GRG170DX una guitarra asequible para rock y metal.', 'https://drunkat.es/es/p/ibanez-grg170dx-bkn-guitarra-electrica-tipo-heavy/9625?gclid=CjwKCAjw8LTmBRBCEiwAbhh-6EPsuXvGu4N--ZEwIqpRIidhBneiSkyr1NiFb15lpN8wLsmCoqHVoxoCeZ4QAvD_BwE', 'https://www.amazon.es/Ibanez-grg120bdx-Guitarra-El%C3%A9ctrica-plano/dp/B00QKV4JLO', 'https://www.gear4music.es/es/Guitarra-y-bajo/DISC-Ibanez-GRG170DX-GIO-Black-Knight/69Q', 'Drunkat', 'Amazon', 'Gear4Music', 'https://www.youtube.com/embed/RdQ16yg7-8k'),
(5, 'badger-classic.png', 'Badger Classic', 'La guitarra eléctrica clásico de tejón es una guitarra única y atractiva que está construida para resistir la prueba del tiempo. Con un Oakeme cuerpo y mástil de arce, esta guitarra es adecuada para todos los instrumentistas de guitarra de principiante a profesional.', 'https://www.amazon.co.uk/Badger-Classic-Electric-Guitar-White/dp/B073QVJCQV', 'https://www.gear4music.es/es/Guitarra-y-bajo/Badger-Classic-Electric-Guitar-All-Black/1WG4', '', 'Amazon', 'Gear4Music', '', 'https://www.youtube.com/embed/O_gv62lVkAg'),
(6, 'bohemian-guitar.png', 'Bohemian Guitars', 'La guitarra Brian May Special es el buque insignia de la gama Brian May Guitars y es el resultado de la colaboración entre el guitarrista de Queen, Pete Malandrone y House Music. Este impresionante modelo cuenta con un cuerpo caoba con cámara acústica y una tapa de caoba que ofrece un tono rico y equilibrado con gran versatilidad. Su cuerpo tiene un elegante doble cutaway, y está equipado con tres pastillas BM Custom Tri-Sonic que ofrecen un rendimiento sin paliativos y una variedad sónica que deslumbra sobre cualquier escenario.', 'https://www.gear4music.es/es/Guitarra-y-bajo/Brian-May-Special-Guitarra-Electrica-Antique-Cherry/1R1K', 'http://shop.brianmayguitars.co.uk/the-bmg-special.html', '', 'Gear4Music', 'Brian May Guitars', '', 'https://www.youtube.com/embed/3cSLKoAfv6U');
